USE [master]
GO

/****** Object:  Database [HW_Karavan_4228]    Script Date: 24.10.2020 13:10:11 ******/
CREATE DATABASE [HW_Karavan_4228]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HW_Karavan_4228', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HW_Karavan_4228.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HW_Karavan_4228_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HW_Karavan_4228_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HW_Karavan_4228].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HW_Karavan_4228] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET ARITHABORT OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HW_Karavan_4228] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HW_Karavan_4228] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HW_Karavan_4228] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HW_Karavan_4228] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET RECOVERY FULL 
GO

ALTER DATABASE [HW_Karavan_4228] SET  MULTI_USER 
GO

ALTER DATABASE [HW_Karavan_4228] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HW_Karavan_4228] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HW_Karavan_4228] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HW_Karavan_4228] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HW_Karavan_4228] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HW_Karavan_4228] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HW_Karavan_4228] SET  READ_WRITE 
GO


